<#
.SYNOPSIS
    Harmonizes and applies metadata string replacements into a raw Chocolatey .nuspec string.

.DESCRIPTION
    The Update-VsCodeNuspecMetadata function injects standardized metadata extracted from the VS Code Marketplace
    into a raw string representation of a Chocolatey .nuspec file.

    It uses regular expressions to securely replace mandatory NuGet fields (such as <title>, <summary>, and <authors>)
    while fully preserving the rest of the XML file's physical layout and structure. Additionally, it conditionally injects
    optional metadata like <docsUrl>, <projectSourceUrl>, and <tags> based on the provided metadata object.

.PARAMETER NuspecContent
    The raw text content of the .nuspec file (usually read via Get-Content -Raw).

.PARAMETER Meta
    A hashtable containing the resolved metadata properties (usually generated by Get-VsCodeNuspecMetadata).
    Expected keys include: Title, Summary, Authors, ProjectUrl, LicenseUrl, MarketplaceUrl,
    Description, DocsUrl, BugTrackerUrl, ProjectSourceUrl, and Tags.

.EXAMPLE
    $nuspecContent = Get-Content "package.nuspec" -Raw
    $meta = Get-VsCodeNuspecMetadata -ExtMeta $rawMeta -ExtensionPublisher "ms-vscode" -ExtensionName "cpptools"
    $updatedContent = Update-VsCodeNuspecMetadata -NuspecContent $nuspecContent -Meta $meta

.INPUTS
    None

.OUTPUTS
    [string]
    The updated text string representing the injected .nuspec file content, ready to be written back to disk.
#>
function Update-VsCodeNuspecMetadata {
    [CmdletBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions', '', Justification = 'Function only performs string manipulation in memory')]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseSingularNouns', '', Justification = 'Matching external API or established domain terminology')]
    param (
        [Parameter(Mandatory = $true)]
        [string]$NuspecContent,

        [Parameter(Mandatory = $true)]
        [hashtable]$Meta
    )

    $NuspecContent = $NuspecContent -replace '(?is)<title>.*?</title>', "<title>$($Meta.Title)</title>"
    $NuspecContent = $NuspecContent -replace '(?is)<summary>.*?</summary>', "<summary>$($Meta.Summary)</summary>"
    $NuspecContent = $NuspecContent -replace '(?is)<authors>.*?</authors>', "<authors>$($Meta.Authors)</authors>"
    $NuspecContent = $NuspecContent -replace '(?is)<projectUrl>.*?</projectUrl>', "<projectUrl>$($Meta.ProjectUrl)</projectUrl>"
    $NuspecContent = $NuspecContent -replace '(?is)<licenseUrl>.*?</licenseUrl>', "<licenseUrl>$($Meta.LicenseUrl)</licenseUrl>"
    $NuspecContent = $NuspecContent -replace '(?is)<releaseNotes>.*?</releaseNotes>', "<releaseNotes>$($Meta.MarketplaceUrl)#changelog</releaseNotes>"

    if ($Meta.ProjectSourceUrl) {
        if ($NuspecContent -match '(?is)<projectSourceUrl>.*?</projectSourceUrl>') {
            $NuspecContent = $NuspecContent -replace '(?is)<projectSourceUrl>.*?</projectSourceUrl>', "<projectSourceUrl>$($Meta.ProjectSourceUrl)</projectSourceUrl>"
        }
        else {
            $NuspecContent = $NuspecContent -replace '(?i)(</packageSourceUrl>)', "`$1`n    <projectSourceUrl>$($Meta.ProjectSourceUrl)</projectSourceUrl>"
        }
    }
    if ($Meta.BugTrackerUrl) {
        if ($NuspecContent -match '(?is)<bugTrackerUrl>.*?</bugTrackerUrl>') {
            $NuspecContent = $NuspecContent -replace '(?is)<bugTrackerUrl>.*?</bugTrackerUrl>', "<bugTrackerUrl>$($Meta.BugTrackerUrl)</bugTrackerUrl>"
        }
        else {
            if ($NuspecContent -match '(?is)</projectSourceUrl>') {
                $NuspecContent = $NuspecContent -replace '(?i)(</projectSourceUrl>)', "`$1`n    <bugTrackerUrl>$($Meta.BugTrackerUrl)</bugTrackerUrl>"
            }
            else {
                $NuspecContent = $NuspecContent -replace '(?i)(</packageSourceUrl>)', "`$1`n    <bugTrackerUrl>$($Meta.BugTrackerUrl)</bugTrackerUrl>"
            }
        }
    }
    if ($Meta.DocsUrl) {
        if ($NuspecContent -match '(?is)<docsUrl>.*?</docsUrl>') {
            $NuspecContent = $NuspecContent -replace '(?is)<docsUrl>.*?</docsUrl>', "<docsUrl>$($Meta.DocsUrl)</docsUrl>"
        }
        else {
            if ($NuspecContent -match '(?is)</bugTrackerUrl>') {
                $NuspecContent = $NuspecContent -replace '(?i)(</bugTrackerUrl>)', "`$1`n    <docsUrl>$($Meta.DocsUrl)</docsUrl>"
            }
            elseif ($NuspecContent -match '(?is)</projectSourceUrl>') {
                $NuspecContent = $NuspecContent -replace '(?i)(</projectSourceUrl>)', "`$1`n    <docsUrl>$($Meta.DocsUrl)</docsUrl>"
            }
            else {
                $NuspecContent = $NuspecContent -replace '(?i)(</packageSourceUrl>)', "`$1`n    <docsUrl>$($Meta.DocsUrl)</docsUrl>"
            }
        }
    }
    if ($Meta.Tags) {
        $NuspecContent = $NuspecContent -replace '(?is)<tags>.*?</tags>', "<tags>$($Meta.Tags)</tags>"
    }

    return $NuspecContent
}
