name: Chocolatey AU Updater

on:
  # schedule:
  #   - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch: # Allow manual triggers
    inputs:
      forced_packages:
        description: "Comma separated list of packages to force update (optional)"
        required: false
      moderation_repush:
        description: "Comma separated list of packages to repush to moderation without timestamping (optional)"
        required: false

jobs:
  au-update:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upgrade Chocolatey
        run: choco upgrade chocolatey -y --no-progress

      - name: Install Chocolatey AU Module
        shell: powershell
        run: |
          Install-Module -Name au -Force -AcceptLicense

      - name: Run AU Updater
        shell: powershell
        env:
          api_key: ${{ secrets.CHOCO_API_KEY }}
          github_user_repo: "philippeganz/chocolatey-vscode-extensions"
          github_api_key: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $forced = "${{ github.event.inputs.forced_packages }}"
          $moderation = "${{ github.event.inputs.moderation_repush }}"

          if ($moderation) {
            ./bin/update_all.ps1 -ModerationRepush $moderation
          } elseif ($forced) {
            ./bin/update_all.ps1 -ForcedPackages $forced
          } else {
            ./bin/update_all.ps1
          }

      - name: Create Pull Request for Updates
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Auto-Update VS Code Extensions [skip ci]"
          title: "🤖 Auto-Update VS Code Extensions"
          body: "Automated package updates generated by the Chocolatey AU Engine."
          branch: "feature/au-updates"
          add-paths: "automatic/*"
